FROM alpine:latest

# Add panel-rs and entrypoint
ARG TARGETPLATFORM
COPY .docker/${TARGETPLATFORM#linux/}/panel-rs-aio /usr/bin/panel-rs

RUN ln -s /usr/bin/panel-rs /usr/local/bin/calagopus-panel
RUN touch /wings-config.yml

ENV OCI_CONTAINER=official-aio

ENTRYPOINT ["/usr/bin/panel-rs"]
